project:
  type: website

website:
  title: "holoviz-quarto-sandbox"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: holoviz.qmd
        text: basic app
      - href: holoviz2.qmd
        text: app


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



